### ISSUE TITLE
On Get doesn't support /id 

### ISSUE THREAD

**Issue by moorthi07** [deployd/dpd-event#12]
Like dpd collection where you can query ,
followers/2aca5c26b1d75aa6 , it will return follower data for that id. 
And On Get event you can read this.id or query.id.

It is not the case in dpd-event. In On Get , I have to use a regular http query and read it this way,
http://localhost:2403/followers?id=2aca5c26b1d75aa6
and in 'On Get' event,
dpd.followers.get{'id': query.id}

Hope this is the feature and this is not clear in the document as developers could expect same or 
 confuse between collection 'On Get' vs dpd-even 'On Get'  url patten like I did.

**Comment by andreialecu** [comment]
See https://github.com/deployd/dpd-event#url

**Comment by moorthi07** [comment]
@andreialecu  parts[0] is good check for id.  My bad, I tried query.url instead at first time.
