### ISSUE TITLE
setResult inside promise resolve is not working

### ISSUE THREAD

**Issue by Tarshith-Vishnu-Teja** [deployd/dpd-event#13]
setResult inside promise resolve is not working and it is returning empty object {}.

var request = require("request");

var options = { method: 'GET',
  url: 'https://sandbox-quickbooks.api.intuit.com/v3/company/123145907152884/invoice/130',
  headers: 
   { 'postman-token': '683dc6ce-5418-635a-ecb0-e20c6f0ba215',
     'cache-control': 'no-cache',
     authorization: 'Bearer eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..o9XTRK1HPyGg_4LDY-cbbg.rCOMTcIUusA4CRms3-ARJNi1z2JYaNCO0YOLh9e6f1lSueLFCI5X9Zc_InPwpLBev9bCjtUP_cnBPnKlPTAYDRhbJZCO3e11_zJUEgHdBfWVHxdys3VImFoDb1hyBqxbQldQh5BcR4VzVSqakl95dZcybgh8_IWikqS4XLVViFI0VsrLnnnBZNGMXqXjT04U56XtJzrNqjZO5gIc_ZfYwOk31-o9p3o9FPbYrega6uL-jul30RBhsbxtj-Y2FBSlLGC0SKgn-a6D6xBOXmfk4-bd75tASf9pCLNzxJpxQsa6zC5anYpR4H-sRJCn3swxtDCzEoONEZFYCMVCsU--cnDIzL4360XdwwSqQozTMT4OqTRX9Us7aO0h5BKRq4bxGRgKGCqfmKrv0v40lJi4q_AtFHJFZciPgfzNVpyA0JoZkuGoRPOBtrTnmWAgvZNXOkofgSyOxaZPftlylYlDIYBAKMg0jyL5EjE3Af9k7CyuhXkVAr0UkI9NzLvKiP4MCnjl7RV-LQ1lzt2-P-vjW9bqgnFaxyWMNbHe7WycqOtfgjcgCTRQmU_6cK7tovnyAPl4MfkMVLmtj_c9ACcip_AlezA3L05GjaiHIWMOgQYrHsgMw-8W_2EOabGuYLcAR635lV6ggHM7Rf3duDZqXStyh9PLvwiHbILZTkAzUR6ezuf6yoWHtEzxlBeavk1H.zIb72zHSmn-3n2KLst9anA',
     accept: 'application/json',
     'user-agent': 'Intuit-qbov3-postman-collection1' },
  body: '{}' };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
  setResult({"speech": "hello!!!!"})
});

**Comment by moorthi07** [comment]
@NicolasRitouet @andreialecu We are stuck returning a custom result from a callback  end.  Is this addressed in the pending PR? In the doc. it shows  it works inside dpd.get call.  Any clue?

**Comment by Tarshith-Vishnu-Teja** [comment]
This code i used from expressJS without dpd and res.send is working.
/**
 * New node file
 */
var ejs = require("ejs");
exports.getInvoice = function(req, res){
	console.log("heya!");
	
	var request = require("request");

	var options = { method: 'GET',
	  url: 'https://sandbox-quickbooks.api.intuit.com/v3/company/123145907152884/invoice/130',
	  headers: 
	   { 'postman-token': '8825602d-9fc4-9ace-25f9-75998e5665d7',
	     'cache-control': 'no-cache',
	     authorization: 'Bearer eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..o9XTRK1HPyGg_4LDY-cbbg.rCOMTcIUusA4CRms3-ARJNi1z2JYaNCO0YOLh9e6f1lSueLFCI5X9Zc_InPwpLBev9bCjtUP_cnBPnKlPTAYDRhbJZCO3e11_zJUEgHdBfWVHxdys3VImFoDb1hyBqxbQldQh5BcR4VzVSqakl95dZcybgh8_IWikqS4XLVViFI0VsrLnnnBZNGMXqXjT04U56XtJzrNqjZO5gIc_ZfYwOk31-o9p3o9FPbYrega6uL-jul30RBhsbxtj-Y2FBSlLGC0SKgn-a6D6xBOXmfk4-bd75tASf9pCLNzxJpxQsa6zC5anYpR4H-sRJCn3swxtDCzEoONEZFYCMVCsU--cnDIzL4360XdwwSqQozTMT4OqTRX9Us7aO0h5BKRq4bxGRgKGCqfmKrv0v40lJi4q_AtFHJFZciPgfzNVpyA0JoZkuGoRPOBtrTnmWAgvZNXOkofgSyOxaZPftlylYlDIYBAKMg0jyL5EjE3Af9k7CyuhXkVAr0UkI9NzLvKiP4MCnjl7RV-LQ1lzt2-P-vjW9bqgnFaxyWMNbHe7WycqOtfgjcgCTRQmU_6cK7tovnyAPl4MfkMVLmtj_c9ACcip_AlezA3L05GjaiHIWMOgQYrHsgMw-8W_2EOabGuYLcAR635lV6ggHM7Rf3duDZqXStyh9PLvwiHbILZTkAzUR6ezuf6yoWHtEzxlBeavk1H.zIb72zHSmn-3n2KLst9anA',
	     accept: 'application/json',
	     'user-agent': 'Intuit-qbov3-postman-collection1' },
	  body: '{}' };

	request(options, function (error, response, body) {
	  if (error) throw new Error(error);

	  console.log(body);
	  res.send({"speech": body.toString()});
	});
	

	
	
}

**Comment by andreialecu** [comment]
@Tarshith-Vishnu-Teja Since you're using a custom async function, you need to manually track callback completion.

Right now you can do it with the functionality described here: https://github.com/deployd/deployd/pull/591

**Comment by moorthi07** [comment]
@andreialecu  Thanks for quick response. 
$addCallback $finishCallback  - are not found in the document. This one more thing to be added to the doc,  right?

**Comment by andreialecu** [comment]
Yes
