### ISSUE TITLE
'me' is undefined. not available

### ISSUE THREAD

**Issue by moorthi07** [deployd/dpd-event#24]
dpd-event not  supporting 'me' as its documented in [http://docs.deployd.com/docs/using-modules/reference/event-api.html]( http://docs.deployd.com/docs/using-modules/reference/event-api.html)

Any idea? 

Was it ever tested?

**Comment by andreialecu** [comment]
It does work. Make sure you're actually logged in and supplying a valid session id via HTTP header or cookie.

**Comment by moorthi07** [comment]
You are right it works with same origin port. Is it working in cross browser mode (different origin).

**Comment by moorthi07** [comment]
Thanks.  I was missing { headers: headers, withCredentials: true }.
