### ISSUE TITLE
the docs are wrong

### ISSUE THREAD

**Issue by ramstein74** [deployd/dpd-event#6]
// On GET /sum
// Return the sum of the a and b properties (/sum?a=5&b=1)

setResult(query.a + query.b);

it does not work.
I get the error 
Typeerror: first argument must be a string or a buffer.

Then i add query.a+query.b and convert to string before setresult.

Regards

**Comment by NicolasRitouet** [comment]
can you send us a PR with the correction?

**Comment by andreialecu** [comment]
Fixed in #15
